### ISSUE TITLE
Reduce the number of revision keys that are sent to the server on prefetch

### ISSUE THREAD

**Issue by mPorhel** [eclipse-cdo/cdo#69]
Behavior introduced with https://bugs.eclipse.org/bugs/show_bug.cgi?id=576893

In our products based on CDO, we do not lazily load content of models but we prefetch some resources one by one.
When moving from CDO 4.7 to CDO 4.22, we encountered performance regressions due to the prefetch indication sending the known revision keys ids. In our case as we want to prefetch resources from their root with an infinite depth.

We could have some option or system preference to enable/disable it.

**Comment by estepper** [comment]
I agree with you that there are probably situations where it's just more efficient to load all children rather than telling the server what children we already have. In all cases that I tested locally it was slower to load all children. In the end it's good to have this configurable, which leaves us with the decision about a good default option.

I'm going to push a change that introduces the new option CDOSession.Option.setPrefetchSendMaxRevisionKeys(). The VM-wide default for this option can be set via -DPREFETCH_SEND_MAX_REVISION_KEYS=n, In the absence of this system property the default value is 100.

**Comment by estepper** [comment]
Please let me know how that works for you ;-)
